# Generated by Django 6.0 on 2025-12-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_options_remove_post_published_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='users_who_liked',
        ),
    ]
